version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://covid_range_user:bwIUYLuFto9IBUg55LJAAzHs0sbD7qSJ@db:5432/covid_range

  db:
    image: postgis/postgis:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: covid_range_user
      POSTGRES_PASSWORD: bwIUYLuFto9IBUg55LJAAzHs0sbD7qSJ
      POSTGRES_DB: covid_range
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
